### ISSUE TITLE
Not build on Linux

### ISSUE THREAD

**Issue by GiacomoLeopizzi** [onevcat/AddressParser#1]
The package does not build on ubuntu. The output is:

AddressParser.swift:31:19: error: use of undeclared type 'RegularExpression'
typealias Regex = RegularExpression
                  ^~~~~~~~~~~~~~~~~

**Comment by GiacomoLeopizzi** [comment]
I solved the problem by changing this: 

#if os(Linux)
typealias Regex = RegularExpression
#else
typealias Regex = NSRegularExpression
#endif

in:

typealias Regex = NSRegularExpression

**Comment by onevcat** [comment]
Fixed in 1.1.0
